theme: jekyll-theme-minimal

# basic configuration
markdown: kramdown
permalink: /:categories/:title/

# Change this tracking code with your own tracking code
# Please leave this code here for us to see how Course in a Box get used

# Some files we need to exclude, so Github can build the site
exclude: [Gemfile, Gemfile.lock, README.md]

defaults:
  -
    scope:
      path: "modules" # an empty string here means all files in the project
    values:
      layout: "course_page"

prose:
  media: img
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /fonts
    - /js
    - /css

